## Travis CI Configuration file

# Use barebones Travis image
language: c

# Install dependencies
before_install:
  - sudo apt-get install -y libudev-dev
addons:
  apt:
    update: true

# Only grab latest git commit (no need for history)
git:
  depth: 1

# Command to run tests
env:
  - EXAMPLE=cli-status
  - EXAMPLE=cli-config

# Command to run tests
script:
  - cd examples/$EXAMPLE && make
